import Head from 'next/head'
import ChangePassword from '../components/change-password'
import LoginForm from '../components/login-form'
import ResetPassword from '../components/reset-password'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cassvita</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="vh-100 d-flex justify-content-center align-items-center">
         <LoginForm />
         <ChangePassword />
         <ResetPassword />
      </main>
     
    </div>
  )
}
